<?php

/**
 * @file
 * Provides support for derived paragraph entity type classes.
 */

/**
 * Implements hook_entity_type_alter().
 */
function discoverable_entity_bundle_classes_paragraphs_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['paragraph'])) {
    $entity_types['paragraph']->setStorageClass('\Drupal\discoverable_entity_bundle_classes\Storage\SqlContentEntityStorageBase');
  }
}
