<?php

/**
 * @file
 * Provides support for derived taxonomy entity type classes.
 */

/**
 * Implements hook_entity_type_alter().
 */
function discoverable_entity_bundle_classes_taxonomy_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['taxonomy_term'])) {
    $entity_types['taxonomy_term']->setStorageClass('\Drupal\discoverable_entity_bundle_classes\Storage\Taxonomy\TermStorage');
  }
}
